server:
  port: 8765
spring:
  application:
    name: eurka-server
  cloud:
    inetutils: 
      preferred-networks: ^106\.12
      ignored-interfaces:
        -eth0
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port} 
  